### ISSUE TITLE
yum ansible module need python2

### ISSUE THREAD

**Issue by tjyang** [MrMEEE/awx-build#151]
* Running on ansible-awx  7.0.*
* Trying to install a yum pkg.

```
---
- name: Install Common packages.
  hosts: all
  tasks:
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
    - name: Install mlocate
      yum:
        name: mlocate
        state: present
<snipped>
```
* error message
```
  "msg": "The Python 2 bindings for rpm are needed for this module.
 If you require Python 3 support use the `dnf` Ansible module instead.. 
The Python 2 yum module is needed for this module.
 If you require Python 3 support use the `dnf` Ansible module instead.",
```

![image](https://user-images.githubusercontent.com/378638/64631611-140a2680-d3bd-11e9-8e4d-beeb68fead93.png)

* References
    * https://github.com/ansible/ansible/issues/32532
    * [ansible yum moudle only work with python2 instance]( https://docs.ansible.com/ansible/latest/modules/yum_module.html)
