### ISSUE TITLE
Task doesnt do any changes in Filesystem

### ISSUE THREAD

**Issue by pwe123345** [MrMEEE/awx-build#180]
Hello,

Im facing an odd issue lately: My task doesnt do anything on my host.

Here is the task:
```
---
- hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: generate ks file for VM
      template:
        src: kickstart.cfg.j2
        dest: "isomaster/isolinux/ks.cfg"
      when: esxi_hostname is defined
```

And the output of the task:
```
Identity added: /tmp/awx_13228_c_ymsg9n/artifacts/13228/ssh_key_data (/tmp/awx_13228_c_ymsg9n/artifacts/13228/ssh_key_data)
ansible-playbook 2.8.6
  config file = None
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible
  executable location = /opt/rh/rh-python36/root/bin/ansible-playbook
  python version = 3.6.3 (default, May 31 2019, 13:05:43) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
No config file found; using defaults
PLAYBOOK: 01_PrepareISO.yml ****************************************************
1 plays in 01_PrepareISO.yml
PLAY [all] *********************************************************************
META: ran handlers
TASK [generate ks file for VM] *************************************************
task path: /tmp/awx_13228_c_ymsg9n/project/01_PrepareISO.yml:7
changed: [FQDN] => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": true, "checksum": "9783f3c828d00f08b2e608112c5e9548e5f070ae", "dest": "isomaster/isolinux/ks.cfg", "gid": 988, "group": "awx", "md5sum": "ef07d3be4f11a6ad8476b6e3c59af040", "mode": "0644", "owner": "awx", "secontext": "system_u:object_r:tmp_t:s0", "size": 3009, "src": "/var/lib/awx/.ansible/tmp/ansible-tmp-1572604672.5396724-154607770465033/source", "state": "file", "uid": 991}
```

The file "isomaster/isolinux/ks.cfg" remains untouched.

Additional information: The Job template is set to "Run" and I cant find any newer version of the file anywhere in the filesystem.
