### ISSUE TITLE
No virtualenv support

### ISSUE THREAD

**Issue by angystardust** [MrMEEE/awx-build#48]
Hi @MrMEEE,
first of all thanks for your effort.
I've noticed that installing your last rpm (2.0.1) it doesn't allow to create custom venv and associate them to an organization. This feature was introduced in tower 3.0 and in 3.3 it was further streamlined:
https://docs.ansible.com/ansible-tower/latest/html/upgrade-migration-guide/virtualenv.html

On a setup using your rpm, I cannot see the "Ansible environment" option at all:
![screenshot from 2018-10-18 20-16-13](https://user-images.githubusercontent.com/1568397/47175147-b8e9c400-d312-11e8-8833-fe29655f4ac5.png)

Is it possible to enable this feature in your rpm?

**Comment by MrMEEE** [comment]
Hi

I think it's related to https://github.com/ansible/awx/issues/1815...

I'll see what I can do...

**Comment by efenex** [comment]
just had this same issue, restarting memcached and logging out/into AWX made the dropdown appear.

**Comment by MrMEEE** [comment]
hmmmm... Not working here :(

**Comment by efenex** [comment]
We are using your 2.0.1 RPM FYI. 

I wrote the following ansible code to create and configure the virtualenv's (maybe it can help you in case the issue is in the configuration):

```
---
- name: AWX | post_install | Install virtualenv package
  package:
    name: "{{ item }}"
  loop:
    - python-virtualenv
    - gcc
 
- name: AWX | post_install | Create virtualenvs
  pip:
    name:
      - pip
      - setuptools
    virtualenv: "/var/lib/awx/venv/ansible-{{ item }}"
  loop: "{{ awx.ansible_versions }}"

- name: AWX | post_install | Install awx dependencies into venv
  pip:
    name:
      - python-memcached
      - psutil
    virtualenv: "/var/lib/awx/venv/ansible-{{ item }}"
  loop: "{{ awx.ansible_versions }}"
 
- name: AWX | post_install | Install ansible inside venv
  pip:
    name: ansible
    version: "{{ item }}"
    virtualenv: "/var/lib/awx/venv/ansible-{{ item }}"
  loop: "{{ awx.ansible_versions }}"
 
#- name: AWX | post_install | Get API token if awx application details are provided
#  uri:
#    url: "http://{{ ansible_fqdn }}/api/o/token/"
#    method: POST
#    body: "grant_type=password&username={{ awx.admin_username }}&password={{ awx.admin_password }}&scope=write"
#    user: "{{ awx.api.username }}"
#    password: "{{ awx.api.password }}"
#    return_content: yes
#  register: token
#  when: "'username' in awx.api and 'password' in awx.api"
 
- name: AWX | post_install | Get API token if awx application details are provided
  command: curl -q -X POST -d "grant_type=password&username={{ awx.admin_username }}&password={{ awx.admin_password }}&scope=write" -u "{{ awx.api.username }}:{{ awx.api.password }}" "http://{{ ansible_fqdn }}/api/o/token/"
  register: token
  run_once: true
  when: "'username' in awx.api and 'password' in awx.api"

- set_fact:
    token: "{{ token.stdout | from_json }}"
 
- name: AWX | post_install | Configure custom venv for orgs when specified
  command: 'curl --request PATCH --data "{\"custom_virtualenv\": \"/var/lib/awx/venv/ansible-{{ item[1] }}/\"}" -H "Content-Type: application/json" -H "Authorization: Bearer {{ token.access_token }}" "http://{{ ansible_fqdn }}/api/v2/organizations/{{ item[0] }}/"'
  run_once: true
  when: "'access_token' in token"
  loop: "{{ awx.ansible_venv_org_mapping }}"

- name: AWX | post_install | Configure custom venv for projects when specified
  command: 'curl --request PATCH --data "{\"custom_virtualenv\": \"/var/lib/awx/venv/ansible-{{ item[1] }}/\"}" -H "Content-Type: application/json" -H "Authorization: Bearer {{ token.access_token }}" "http://{{ ansible_fqdn }}/api/v2/projects/{{ item[0] }}/"'
  run_once: true
  when: "'access_token' in token"
  loop: "{{ awx.ansible_venv_project_mapping }}"

- name: AWX | post_install | Configure custom venv for job templates when specified
  command: 'curl --request PATCH --data "{\"custom_virtualenv\": \"/var/lib/awx/venv/ansible-{{ item[1] }}/\"}" -H "Content-Type: application/json" -H "Authorization: Bearer {{ token.access_token }}" "http://{{ ansible_fqdn }}/api/v2/job_templates/{{ item[0] }}/"'
  run_once: true
  when: "'access_token' in token"
  loop: "{{ awx.ansible_venv_jobtemplate_mapping }}"
```
