### ISSUE TITLE
set_stats not working

### ISSUE THREAD

**Issue by bamason14** [MrMEEE/awx-build#93]
I am trying to set and reference set_stats in a workflow. In first playbook I am setting the following:

```yaml
  - name: yum update
    yum:
      name: '*'
      state: latest
    register: yum_update
    when: (ansible_distribution_major_version >= "6")
    
  - debug:
      msg: '{{ yum_update }}'
    
  - name: set stats
    set_stats:
      data:
        patching_result: '{{ yum_update.changed }}'
      per_host: yes


  - debug:
      msg: "{{ patching_result }}"
```
The result is variable is not being set. 

I get the following warning  in the first playbook.

CUSTOM STATS: ******************************************************************
 [WARNING]: Failure using method (v2_playbook_on_stats) in callback plugin
(<display_callback.module.AWXDefaultCallbackModule object at 0x7ffb8f9602b0>):
'<' not supported between instances of 'Host' and 'Host'

Second playbook I am trying to reference variable in the following when statement:

`when: (facter_is_virtual|bool  == true) and (patching_result == false)`

Error is undefined variable. 

Am I miss understanding on how set_stats is suppose to work or is there a bug or installation issue?
